# Generated by Django 4.1.4 on 2023-04-15 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='React',
        ),
    ]
