# Generated by Django 4.1.4 on 2023-04-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.BigIntegerField()),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('sale_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'sales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.BigIntegerField()),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('supply_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'supplies',
                'managed': False,
            },
        ),
    ]
