# Generated by Django 4.1.4 on 2023-04-15 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sales_supplies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
        migrations.DeleteModel(
            name='Supplies',
        ),
    ]
